
services:
  minio:
    image: minio/minio:latest
    container_name: minio-secure
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=admin4030
      - MINIO_ROOT_PASSWORD=SuperSecurePassword123!
      - MINIO_KMS_SECRET_KEY=my-minio-key:XTp6urxoHlNxgBq5trWkKsV1k1HXZro358VQx4Mw97I=
    volumes:
      - ./data:/data:Z
      - ./certs:/root/.minio/certs:Z
    command: server /data --console-address ":9001"
    restart: unless-stopped